# Generated by Django 2.2.2 on 2019-06-28 13:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Qurilish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q_type', models.CharField(max_length=100, null=True)),
                ('servise_name', models.CharField(max_length=100, null=True)),
                ('servise_code', models.CharField(max_length=5, null=True)),
                ('soato', models.CharField(max_length=6, null=True)),
                ('report_month', models.CharField(max_length=6, null=True)),
                ('report_year', models.CharField(max_length=6, null=True)),
                ('last_year', models.CharField(max_length=6, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
